# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Directory.Build.props", "."]
COPY ["nuget.config", "."]
COPY ["src/Client/TicketSystem.WebApi/TicketSystem.WebApi.csproj", "src/Client/TicketSystem.WebApi/"]
COPY ["src/Business/TicketSystem.Business/TicketSystem.Business.csproj", "src/Business/TicketSystem.Business/"]
COPY ["src/Common/TicketSystem.Dto/TicketSystem.Dto.csproj", "src/Common/TicketSystem.Dto/"]
COPY ["src/Common/TicketSystem.Enums/TicketSystem.Enums.csproj", "src/Common/TicketSystem.Enums/"]
COPY ["src/DataAccess/TicketSystem.DataAccess.Contract/TicketSystem.DataAccess.Contract.csproj", "src/DataAccess/TicketSystem.DataAccess.Contract/"]
COPY ["src/DataAccess/TicketSystem.DataAccess.Entity/TicketSystem.DataAccess.Entity.csproj", "src/DataAccess/TicketSystem.DataAccess.Entity/"]
COPY ["src/Common/TicketSystem.Translate/TicketSystem.Translate.csproj", "src/Common/TicketSystem.Translate/"]
COPY ["src/Business/TicketSystem.Business.Contract/TicketSystem.Business.Contract.csproj", "src/Business/TicketSystem.Business.Contract/"]
COPY ["src/DataAccess/TicketSystem.DataAccess/TicketSystem.DataAccess.csproj", "src/DataAccess/TicketSystem.DataAccess/"]
COPY ["src/DataAccess/TicketSystem.DataAccess.Context/TicketSystem.DataAccess.Context.csproj", "src/DataAccess/TicketSystem.DataAccess.Context/"]
COPY ["src/Common/TicketSystem.Common/TicketSystem.Common.csproj", "src/Common/TicketSystem.Common/"]
RUN dotnet restore "./src/Client/TicketSystem.WebApi/TicketSystem.WebApi.csproj"
COPY . .
WORKDIR "/src/src/Client/TicketSystem.WebApi"
RUN dotnet build "./TicketSystem.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TicketSystem.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TicketSystem.WebApi.dll"]